CREATE TABLE IF NOT EXISTS au_role (
    id VARCHAR(36) PRIMARY KEY COMMENT '角色ID (UUID)',
    role_name VARCHAR(100) NOT NULL UNIQUE COMMENT '角色名称',
    description VARCHAR(255) DEFAULT NULL COMMENT '角色描述',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
    );
