spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/keyauth
    username: keyAuth
    password: jymbFGkKDWhsxnF8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1          # Redis 服务器地址
    port: 6379                   # Redis 服务器端口
logging:
  config: classpath:logback-dev.xml  # 指定 Logback 配置文件路径

CAuth:
  isPrintSQL : true
  version: V1.0.0.3