server:
  port: 8080
spring:
  profiles:
    active: dev #切换环境
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # 避免 Spring Boot 自动创建数据库
  liquibase:
    change-log: classpath:db.changelog-master.xml
mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml  # 扫描 mappers 文件夹下的所有 XML 文件

CAuth:
  Login-ExpireTime : 100
