spring:
  datasource:
    url: jdbc:mysql://100.76.189.100:3306/keyAuth
    username: cc
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.4.1              # Redis 服务器地址
    port: 6379                   # Redis 服务器端口
logging:
  config: classpath:logback-dev.xml  # 指定 Logback 配置文件路径

CAuth:
  isPrintSQL : true
  version: V1.0.0.1